---

Parameters:
  FileExpirationInDays:
    Description: How many days until a file in this bucket is deleted?
    Type: Number
    MinValue: 1
    # 5 x 365
    MaxValue: 1825
    Default: 1825

Resources:
  TheKitchenSinkS3Bucket:
    Type: AWS::S3::Bucket
    # Protect from accidental stack deletion
    DeletionPolicy: Retain
    Properties:
      # AccelerateConfiguration:
      #   AccelerateConfiguration
      # AccessControl: PublicRead
      # AnalyticsConfigurations:
      #   - AnalyticsConfiguration
      #BucketEncryption:
      #  ServerSideEncryptionConfiguration:
      #  - ServerSideEncryptionByDefault:
      #      SSEAlgorithm: aws:kms
      #      KMSMasterKeyID: arn:aws:kms:us-east-1:123456789012:key/9010425e-f447-41ef-ba5d-cf30aa5f69bb
      BucketName: kitchen-sink
      # CorsConfiguration:
      #   CorsConfiguration
      # InventoryConfigurations:
      #   - InventoryConfiguration
      LifecycleConfiguration:
        Rules:
        - Id: my-lifecycle-rules
          Status: Enabled
          ExpirationInDays: !Ref FileExpirationInDays
      # LoggingConfiguration:
      #   LoggingConfiguration
      # MetricsConfigurations:
      #   - MetricsConfiguration
      # NotificationConfiguration:
      #   NotificationConfiguration
      # ObjectLockConfiguration:
      #   ObjectLockConfiguration
      # ObjectLockEnabled: Boolean
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      # ReplicationConfiguration:
      #   ReplicationConfiguration
      Tags:
        -
          Key: "foo"
          Value: "bar"
        -
          Key: "keymaster"
          Value: "gatekeeper"
      # VersioningConfiguration:
      #   VersioningConfiguration
      # WebsiteConfiguration:
      #   WebsiteConfiguration

Outputs:
  TheGlobalDefaultS3Bucket:
    Description: My default S3 bucket when a CloudFormation scripts needs a bucket for something quick and dirty
    Value: !Ref TheKitchenSinkS3Bucket
    Export:
      Name: GlobalDefaultS3Bucket
