---
Parameters:
  VPCNameTag:
    Description: Name tag that will be assigned to the VPC
    Type: String
    Default: stack-created-vpc

Resources:
  MyStackCreatedVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 192.168.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
       - Key: Name
         Value: !Ref VPCNameTag
       - Key: creator-stack-name
         Value: !Ref AWS::StackName
       - Key: creator-stack-id
         Value: !Ref AWS::StackId

Outputs:
  MyStackCreatedVPCOutput:
    Value: !Ref MyStackCreatedVPC
    Description: VPC id of my stack-created VPC
    Export:
      Name: StackCreatedVPC
