---
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-035b3c7efe6d061d5
      InstanceType: t2.micro
      #SecurityGroups:
      #  - !Ref MySecurityGroupForSshAndHttp
      SecurityGroupIds:
        - !Ref MySecurityGroupForSshAndHttp
      SubnetId: !ImportValue StackCreatedSubnetA

  MySecurityGroupForSshAndHttp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP connections from anywhere
      GroupName: sec-grp-for-ssh-and-http-to-my-ec2
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      VpcId: !ImportValue StackCreatedVPC

  #MyElasticIpForEC2Instance:
  #  Type: AWS::EC2::EIP
  #  Properties:
  #    InstanceId: !Ref MyEC2Instance
