---
Parameters:
  KeyPairName:
    # On CloudFormation console, will display dropdown list of keypairs for account
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair


Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-035b3c7efe6d061d5
      InstanceType: t2.micro
      KeyName:
        Ref: KeyPairName
      SecurityGroupIds:
        - !Ref mySecurityGroupForSshAndHttp
      SubnetId: !ImportValue StackCreatedSubnetA
      Tags:
      - Key: Name
        Value: stack-created-vpc-ec2-instance
  mySecurityGroupForSshAndHttp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP connections from anywhere
      GroupName: sec-grp-for-ssh-and-http-to-my-ec2
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      VpcId: !ImportValue StackCreatedVPC
  myElasticIpForEC2Instance:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref myEC2Instance
